Add WYSIWYG & Block Editor as Extensions
directus-labs/extensions pull request #39
Opened 2024-08-14 07:49 UTC by formfcw

Should meet the requirements. I've added some examples of how to extend each of the editors in the README files.

2024-08-26 20:48 UTC, ComfortablyCoding requested changes
### Build Stage Issues
I receive the following warnings when attempting to build these extensions.

<img width="1431" alt="Screenshot 2024-08-26 at 4 34 25 PM" src="https://github.com/user-attachments/assets/20c01d7e-42a6-4506-8228-7e281925b6a9">
<img width="1326" alt="Screenshot 2024-08-26 at 4 36 26 PM" src="https://github.com/user-attachments/assets/69deef5b-16a3-4c09-9bc0-37ed849761b9">

### Usage
Although the extensions are enabled and show under the extensions tab they do not show up in the `Interface` section for the respective fields

2024-08-26 20:48 UTC, ComfortablyCoding commented on packages/input-block-editor/README.md
> +    https://github.com/directus-labs/extensions/blob/cc0d8fcf2503a5be940bfee13d3e0c022494e106/packages/input-block-editor/src/index.ts#L77-L80
```suggestion
    https://github.com/directus-labs/extensions/blob/main/packages/input-block-editor/src/index.ts#L77-L80
```
Referenced links (here and in other locations) should be to main, this will ensure it will always display the latest preview.

2024-08-27 05:51 UTC, formfcw commented
> ### Build Stage Issues
> 
> I receive the following warnings when attempting to build these extensions.
> <img alt="Screenshot 2024-08-26 at 4 34 25 PM" width="1431" src="https://private-user-images.githubusercontent.com/44623501/361572155-20c01d7e-42a6-4506-8228-7e281925b6a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzY1MzMsIm5iZiI6MTcyNDczNjIzMywicGF0aCI6Ii80NDYyMzUwMS8zNjE1NzIxNTUtMjBjMDFkN2UtNDJhNi00NTA2LTgyMjgtN2UyODE5MjViNmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTAwZDAxYThkZmZmOTcyYTE1ZGUwNDM5ZTk5MmIxYzE2OWM5MWJkMzIxYmNiZTliN2I4NDQ0NjhhZGIyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a_6zquhi3GVx5XmsK5fF4JqhYa60x6l2WSo1NasHZd4"> <img alt="Screenshot 2024-08-26 at 4 36 26 PM" width="1326" src="https://private-user-images.githubusercontent.com/44623501/361572215-69deef5b-16a3-4c09-9bc0-37ed849761b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MzY1MzMsIm5iZiI6MTcyNDczNjIzMywicGF0aCI6Ii80NDYyMzUwMS8zNjE1NzIyMTUtNjlkZWVmNWItMTZhMy00YzA5LTliYzAtMzdlZDg0OTc2MWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA1MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMjg5MDkzMzYzOTgxMDI5NDA5ZWE5YTIwNmNhYzE1MTg4NThkOGEzYThlOTljYmNkMmI1NTcwYjYwZDA2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9E46ud7N7AOLx_YEcVYveQQ0hM-zWWoDjXeass5Dz9w">
> ### Usage
> 
> Although the extensions are enabled and show under the extensions tab they do not show up in the `Interface` section for the respective fields



I am afraid I can’t reproduce your issues. This is what it looks like when I build the extension:

![terminal](https://github.com/user-attachments/assets/b117dfb8-f747-4a33-86fd-072fe1642221)

And this is what the interface selector looks like:

![interface-selector](https://github.com/user-attachments/assets/42016c7d-3850-4aae-84cc-46a176fc3f2c)

Dockerfile:
```Dockerfile
COPY directus-labs/extensions/packages/input-rich-text-html/dist ./extensions/input-rich-text-html/dist
COPY directus-labs/extensions/packages/input-rich-text-html/package.json ./extensions/input-rich-text-html

COPY directus-labs/extensions/packages/input-block-editor/dist ./extensions/input-block-editor/dist
COPY directus-labs/extensions/packages/input-block-editor/package.json ./extensions/input-block-editor
```

What environment are you using?
Did you build the extensions before installing/adding them to the Directus container?

2024-08-27 13:35 UTC, ComfortablyCoding commented
@formfcw 

They do not show up for me

<img width="862" alt="Screenshot 2024-08-27 at 9 31 05 AM" src="https://github.com/user-attachments/assets/4052bb02-edea-4f9c-b5e5-fe21a3eb6981">
<img width="920" alt="Screenshot 2024-08-27 at 9 31 18 AM" src="https://github.com/user-attachments/assets/b55f699b-a740-4119-9a0b-1aa60096ea41">

> What environment are you using?
 
I am using a Mac M3, running directus via the `docker-compose.yml` [from the docs](https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose). The extensions are located in the `extensions` folder.

> Did you build the extensions before installing/adding them to the Directus container?

Yes, the build command is what shows those messages, they also show again when directus is started.

2024-08-28 06:02 UTC, formfcw commented
So, I tried to reinstall everything to a new folder. So I tried to emulate your environment: While I am on a M1, I used the same `docker-compose.yml` [from the docs](https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose), as you did. Then I copied the extensions directly from the GitHub branch into the project folder, installed their dependencies and ran the `build` command.

Block Editor:
![block-editor-build](https://github.com/user-attachments/assets/1ea60be8-2fd3-47cb-a562-00d93cfd2e05)

WYSIWYG:
![wysiwyg-build](https://github.com/user-attachments/assets/fa725cfc-ac71-4c96-b02a-f58f14d20965)

(Yes, there is a (different) warning, that I don’t think we can fix, at the same time it builds successfully!)

Then I ran `docker compose up`, opened Directus, created a new collection and added the fields and interfaces via the selector:

![interface-selector](https://github.com/user-attachments/assets/3c398fe0-e396-44b8-a727-2c9a88fb6299)

And on the item page, they just work:

![interfaces](https://github.com/user-attachments/assets/0e176a86-6171-497b-b1b4-c23b2212bdad)

So, I don’t think that I can reproduce your issues.
Can you (or someone else on your team) try to reinstall in the same way I described above?

2024-08-28 11:56 UTC, ComfortablyCoding commented
> So, I tried to reinstall everything to a new folder. So I tried to emulate your environment: While I am on a M1, I used the same `docker-compose.yml` [from the docs](https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose), as you did. Then I copied the extensions directly from the GitHub branch into the project folder, installed their dependencies and ran the `build` command.
> 
> Block Editor:
> ![block-editor-build](https://github.com/user-attachments/assets/1ea60be8-2fd3-47cb-a562-00d93cfd2e05)
> 
> WYSIWYG:
> ![wysiwyg-build](https://github.com/user-attachments/assets/fa725cfc-ac71-4c96-b02a-f58f14d20965)
> 
> (Yes, there is a (different) warning, that I don’t think we can fix, at the same time it builds successfully!)
> 
> Then I ran `docker compose up`, opened Directus, created a new collection and added the fields and interfaces via the selector:
> 
> ![interface-selector](https://github.com/user-attachments/assets/3c398fe0-e396-44b8-a727-2c9a88fb6299)
> 
> And on the item page, they just work:
> 
> ![interfaces](https://github.com/user-attachments/assets/0e176a86-6171-497b-b1b4-c23b2212bdad)
> 
> So, I don’t think that I can reproduce your issues.
> Can you (or someone else on your team) try to reinstall in the same way I described above?

These were the steps I did as well, I will see if someone else on the team can reproduce the same issues.

2024-08-28 13:48 UTC, ComfortablyCoding requested changes
Re-trying with npm works and have been informed that is acceptable so we can disregard the build issues with pnpm.

2024-08-28 13:48 UTC, ComfortablyCoding commented on packages/input-rich-text-html/src/input-rich-text-html.vue
> +        let styleFormats = null;
```suggestion
        let styleFormats: CustomFormat[] | null = null;
```

2024-08-28 13:48 UTC, ComfortablyCoding commented on packages/input-block-editor/README.md
I believe their is a missing step 5 which is to enable the Marker in the toolbar under the field interface options
 
<img width="851" alt="Screenshot 2024-08-28 at 9 46 09 AM" src="https://github.com/user-attachments/assets/593dd458-f83b-4649-b754-4545b9495db3">

2024-08-28 18:43 UTC, formfcw commented on packages/input-block-editor/README.md
That is what second point in the README does:

https://github.com/directus-labs/extensions/blob/72e5f88d576e909f44c2cba14e24b258f4273649/packages/input-block-editor/README.md?plain=1#L10-L12

2024-08-28 18:49 UTC, formfcw commented
> Re-trying (install and build) with npm works and have been informed that is acceptable so we can disregard the build issues with pnpm.

Oh, I didn’t know you were using `pnpm` … much ado about nothing

2024-08-28 18:55 UTC, ComfortablyCoding commented on packages/input-block-editor/README.md
In that case I will retry this as it did not enable it for me after doing all the steps.

2024-08-28 18:58 UTC, formfcw commented on packages/input-block-editor/README.md
> I believe we should add a step 5 which is to enable the Marker in the toolbar under the field interface options
> <img alt="Screenshot 2024-08-28 at 9 46 09 AM" width="851" src="https://private-user-images.githubusercontent.com/44623501/362306036-593dd458-f83b-4649-b754-4545b9495db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzE2OTEsIm5iZiI6MTcyNDg3MTM5MSwicGF0aCI6Ii80NDYyMzUwMS8zNjIzMDYwMzYtNTkzZGQ0NTgtZjgzYi00NjQ5LWI3NTQtNDU0NWI5NDk1ZGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE4NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZDkyMjAwZTQ3NjYxYzRiZTBmMzc0Mzg2NGQ3YzUwYTRkYzFlYjU2NWYxMjZmNDhiZDM5ZTVhMjFiYWEzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svg1V8XXiUREX6Sw32HE-I3kzme0fIuQwRjhk8emLeY">

Look at the first list item :)

2024-08-28 19:08 UTC, ComfortablyCoding commented on packages/input-block-editor/README.md
I did that manually

2024-08-28 19:25 UTC, ComfortablyCoding commented on packages/input-block-editor/README.md
Based on investigation it is indeed not selected after the outlined steps. Adding `marker` to the `schema.default_values` for the `tools` field does resolve this issue.

2024-08-29 05:29 UTC, formfcw commented on packages/input-block-editor/README.md
I have updated the README

2024-08-29 12:26 UTC, ComfortablyCoding submitted a review, later dismissed
LGTM 🚀

2024-09-02 11:13 UTC, phazonoverload approved these changes

2024-09-02 11:13 UTC, merged