Scatter Plot Panel
directus-labs/extensions pull request #63
Opened 2024-09-21 16:10 UTC by timio23

2024-10-09 09:32 UTC, formfcw requested changes
Great work @timio23 🎉 

In addition to the comments in the code, here is a list of things I noticed while visually reviewing the extension. Please be sure to update the code to at least fix the bugs!

1. Decimal values do not affect the X-axis
    <details><summary>screenshot</summary>

    ![bug-decimal-values](https://github.com/user-attachments/assets/232af2ac-1a5c-412c-a3d2-b34f68f7ddc5)

    </details>

2. The dots do not align with the x-axis label when the field is a datetime or timestamp field
    <details><summary>screenshot</summary>

    ![datetime-int-dot-alignment](https://github.com/user-attachments/assets/9a089c3a-ef6e-4e17-9132-0af6a81253b2)

    </details>

3. Currently there are two tooltips, we could get rid of the bottom one
    <details><summary>screenshot</summary>

    ![double-tooltip](https://github.com/user-attachments/assets/f9ede07b-3988-498a-8519-9a1c5b8fc880)

    </details>

4. If you hover over a dot, it gets bigger and its opacity is reduced; if tooltips are disabled, it just reduces the opacity without getting bigger. Make sure you are consistent here. I would suggest just scaling the dot up a bit on hover or changing the opacity to 100%.
    <details><summary>screenshots</summary>

    ![hover-dot-tooltip](https://github.com/user-attachments/assets/199ce101-46a3-4c03-a4b9-2ed6cd94d820)
    ![hover-dot](https://github.com/user-attachments/assets/d738b8b8-e54f-45d4-93de-60c88266d273)

    </details>

5. When you click on a dot, it gets a gray border, which seems unintentional. You could set its opacity to 100% and remove the border (or make it white) instead.

6. You could change the format of the tooltips from …
    ```js
    `{{ valueOfXAxis }}`
    `{{ colorDot }} {{ collectionName }}: {{ valueOfYAxis }}`
    // or with Series Grouping enabled
    `{{ colorDot }} {{ seriesGroupName }}: {{ valueOfYAxis }}`
    ```
    … to …
    ```js
    `{{ fieldNameOfXAxis }}: {{ valueOfXAxis }}`
    `{{ colorDot }} {{ fieldNameOfYAxis }}: {{ valueOfYAxis }}`
    // or with Series Grouping enabled
    `{{ colorDot }} {{ seriesGroupName }} – {{ fieldNameOfYAxis }}: {{ valueOfYAxis }}`
    ```

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/package.json
> +		"host": "^9.23.3"
Add v11 to host, like `"host": "^10.0.0 || ^11.0.0"`. Otherwise it will be marked as `Compatibility not guaranteed` in the marketplace

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/src/panel.vue
> +import { abbreviateNumber } from '@directus/shared/utils';
Replace with `import { abbreviateNumber } from '@directus/utils';` as it is now located here. Don’t forget to add it to your `package.json`.

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/package.json
> +		"@directus/format-title": "^11.0.0",
Add `@directus/utils` to have access to `abbreviateNumber`

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/src/panel.vue
> +			default: '',
`default` for `series` prop should be `null`, otherwise you will get a bad request error, if you try to add a panel without selecting a field for `Series Grouping`.

![bug-series-default](https://github.com/user-attachments/assets/7c515efe-578f-40b5-8b82-28c792c033b2)

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/src/index.ts
> +						placeholder: '$t:select_a_field',
add `allowNone: true` to the `options` to be able to remove the selection on `Series Grouping`

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/src/panel.vue
> +import { defineComponent, computed, onMounted, onUnmounted, ref, watch } from 'vue';
could remove `computed`

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/README.md
> +![Scatter Plot Panel](./docs/directus-panel-scatter-plot.jpg)
Replace the path with https://raw.githubusercontent.com/directus-labs/extensions/main/packages/scatter-plot-panel/docs/directus-panel-scatter-plot.jpg

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/README.md
> +![Customise the panel](./docs/directus-panel-scatter-plot-customize.jpg)
Replace the path like above

2024-10-09 09:32 UTC, formfcw commented on packages/scatter-plot-panel/README.md
> +Refer to the Official Guide for details on installing the extension from the Marketplace or manually.
Add link `[Official Guide](https://docs.directus.io/extensions/installing-extensions.html)`

2024-10-11 19:11 UTC, timio23 commented
Hi @BB-Loft, I’ve been overseas this week and just got home. I will look at this tonight

2024-10-12 00:00 UTC, timio23 commented
Thanks for your comments @formfcw, I've addressed most of the comments.

1. Wasn't able to reproduce this. X Axis working perfectly for me as integer, decimal and float. Could you provide more information on how you reached this result?
2. The X axis for datetime values are factoring the time when plotting. If I set the time points to exactly midnight, the dots line up perfectly. This should be more visible with the recent changes to the tooltips. (It seems the Directus datetime picker defaults to midday)
3. Bottom tooltip removed as requested
4. Dots now remain the same size. Opacity is the only change
5. Yes, this was unintentional. Stroke has now been removed when a dot is clicked.
6. Tooltip formatting was a little strict when I keep the automations in place. I went for a similar approach along the lines of what you suggested.

```
`{{ fieldNameOfXAxis }}: {{ valueOfXAxis }}`
`{{ colorDot }} {{ collectionName }}: {{ fieldNameOfYAxis }} {{ valueOfYAxis }}`
// Series Grouping enabled
`{{ colorDot }} {{ seriesGroupName }}: {{ fieldNameOfYAxis }} {{ valueOfYAxis }}`
```

Changes to dependencies, readme and index have been made as suggested.

2024-10-12 11:39 UTC, formfcw requested changes
Thanks @timio23! A few things …

~~> 1. Wasn't able to reproduce this. X Axis working perfectly for me as integer, decimal and float. Could you provide more information on how you reached this result?~~

~~I am still running into this problem. I'm using MySQL - maybe that's the reason. Can you test?~~

**(Update: see below)**

---

> 2. The X axis for datetime values are factoring the time when plotting. If I set the time points to exactly midnight, the dots line up perfectly. This should be more visible with the recent changes to the tooltips. (It seems the Directus datetime picker defaults to midday)

You are right with that the date picker defaults to midday, at the same time it still doesn’t align well, even if I set the value to 12 AM (`00:00`).

![](https://github.com/user-attachments/assets/70d7e18b-fbab-4c9d-8c1c-6d4a26419df0)

2024-10-12 11:39 UTC, formfcw commented on packages/scatter-plot-panel/package.json
> +		"@directus/extensions-sdk": "9.23.3",
If there is no specific reason, please use the latest sdk version `12.1.0`.

2024-10-12 11:39 UTC, formfcw commented on packages/scatter-plot-panel/src/panel.vue
> +								let formattedValue = type == 'datetime' ? format(value, (xField.type == 'date' ? "MMM d" : "PPp")) : value > 10000
Make sure to be consistent with the date format: use `xField.type == 'date' ? "MMM d" : "MMM d, p"` or `xField.type == 'date' ? "PP" : "PPp"`

2024-10-12 11:39 UTC, formfcw commented on packages/scatter-plot-panel/src/panel.vue
> +								return `${xField.name}: ${formattedValue}`;
This `n` function causes an error when using decimals (for the x-axis). This error occurs when I hover over a dot. When I use type `float`, it works fine.

2024-10-12 11:50 UTC, formfcw commented
I have now tested with `sqlite3` where it works fine. So maybe this is just related to MySQL ...

2024-10-12 11:50 UTC, formfcw commented on packages/scatter-plot-panel/src/panel.vue
> +								return `${xField.name}: ${formattedValue}`;
works with `sqlite3`

2024-10-12 12:22 UTC, formfcw commented
OK, @timio23. Please make sure that decimal values (for x-axis) work at least with `sqlite3` and `Postgres` as db.

2024-10-14 15:59 UTC, timio23 commented
@formfcw, the datetime alignment seems to be a UTC issue. I found a parameter that disables UTC on the x-axis so it uses your devices local time instead. This should align to your chosen timepoints now. As for the decimals and floats, I've forced the value to a string in the hope it will standardize the data sent to Apex charts. Theoretically Knex should be returning the data in the same way regardless of the database.

2024-10-15 09:11 UTC, formfcw requested changes
Thank you @timio23. I have tested your panel with postgres db and here I have the same problem with `decimal` values on the x-axis. All the dots align to zero and when I hover over a dot I get a console error. Please make sure it works.

2024-10-15 15:52 UTC, timio23 commented
@formfcw, I managed to replicate the issue. The api returns the floats and decimals as strings instead of numbers. Forced the strings to numbers by using * 1. Does this work for you as well?

2024-10-16 05:38 UTC, formfcw submitted a review, later dismissed
LGTM 🚀 Thank you!

2024-11-05 14:29 UTC, phazonoverload submitted a review, later dismissed

2024-11-05 14:32 UTC, phazonoverload approved these changes

2024-11-05 14:34 UTC, phazonoverload approved these changes

2024-11-05 14:34 UTC, merged