Timeline, Funnel, and Tree Map Panels
directus-labs/extensions pull request #78
Opened 2024-10-23 14:25 UTC by timio23

2024-11-04 11:53 UTC, HimoriTempest requested changes
Greetings @timio23 ,
my tests revealed that your extensions compile but don't load.
Would you be able to share under which version this has been tested on your end?
Keep in mind that all extensions should be working on version 11.0.0 and higher.

2024-11-04 13:50 UTC, timio23 commented
Hi @HimoriTempest, that's odd. I test on versions 11.1.1 and 10.13.3. Did you get any console errors?

2024-11-04 14:50 UTC, timio23 commented
@HimoriTempest, found a missing dependancy on the funnel chart. Does that fix the issue?

2024-11-05 14:14 UTC, HimoriTempest requested changes
Looks good to me 🚀 
I don't see the Y and X axis labels.
Are they hidden on purpose?

2024-11-05 14:14 UTC, HimoriTempest commented on packages/funnel-chart-panel/src/panel.vue
> +import { abbreviateNumber } from '@directus/shared/utils';
`abbreviateNumber` can now be found in @directus/utils

This fixes the mentioned issues about loading the extension as I've noticed this error in the logs: 

> "@directus/shared/utils" is imported by "data/prod/extensions/funnel-chart-panel/dist/index.js", but could not be resolved – treating it as an external dependency.

2024-11-05 14:14 UTC, HimoriTempest commented on packages/funnel-chart-panel/src/panel.vue
> +import { abbreviateNumber } from '@directus/shared/utils';
In addition to the change above, the timeline chart seems to be missing the grouping labels on the Y axis and dates on the X as per the spec for this. In addition it always seems to use the total time as display text regardless of what's chosen:
![image](https://github.com/user-attachments/assets/5c94e853-2de4-43a3-8833-6e4a2e9f3205)
ApexChart example:
![image](https://github.com/user-attachments/assets/82fd26d2-c9b7-4a0e-a284-0ded0500fcf4)

2024-11-06 00:15 UTC, timio23 commented on packages/funnel-chart-panel/src/panel.vue
> +import { abbreviateNumber } from '@directus/shared/utils';
I'll look into the total time always displaying, but as for the X and Y labels, these are hidden when the panel is small. I decided to follow suite of the built-in Directus charts which do the same thing.

2024-11-06 10:44 UTC, HimoriTempest reviewed
Looks good to me🚀

2024-11-06 10:52 UTC, HimoriTempest commented on packages/funnel-chart-panel/src/panel.vue
> +import { abbreviateNumber } from '@directus/shared/utils';
Thanks for the clarification

2024-11-06 10:53 UTC, HimoriTempest approved these changes

2024-11-06 17:58 UTC, phazonoverload commented
Hi! Small final changes as a result of our creative review.

## Funnel Chart
- Text in tooltip does not match to the funnel color change
- Tooltip background needs to change from white to dark according to the modes.
- The 'gaps' between the segments - can they also be darker in dark mode or is it a pain? 

## Timeline Chart
- Text in tooltip does not match to the timeline color change
- Start Date + Date End field should we together side-by-side in options - can you put the two sort options and the two date options together? 
- The bar border radius seems to be 0px compared to the other charts with bars that have a slightly rounded corners.
- Tooltip background needs to change from white to dark according to the modes.
- All the colors have an partial opacity of 0.66 - can it be at 1 please? 
- remove option to do multi-series (grouping). 
- Add a delimiter between the task name and number of days (suggesting a colon)
- In dark mode, remove the 

## Tree Map Chart
- Change the white border to fit the dark mode theme
- Remove all hover/active states for segments.
- Can we lower the range between the base color and the lightest color? Lightest ones can be too light. 
- Remove the hashes/lines on the very bottom. Can be quite noticable in dark mode.
  ![image](https://github.com/user-attachments/assets/6b56ff29-f5c5-4104-8586-843b2de65350)
- Can we show the value on the data label after a colon. Currently “Phase 2” should it be “Phase 2: 000"

2024-11-14 14:52 UTC, timio23 commented
@BB-Loft I've uploaded the latest changes.

@phazonoverload, thanks for your suggestions. I have the following notes:
- Apexcharts doesn't have an option to change the funnel chart gap color. I can change it using CSS but it wouldn't match the chosen colour anymore. It would be need to be a static value or a css theme variable.
- The timeline opacity is for overlapping timelines. Do you still want the opacity changed to 1?
<img width="303" alt="image" src="https://github.com/user-attachments/assets/2419807a-ff9a-4b7c-a0a0-20324a187798">
- I've removed the grouping from the timeline chart but since it's optional, wouldn't it be better to leave it in?
- Rather than remove the hover tooltip on the treetop charts, I've disabled the tooltip by default. If they choose to hide the labels, I think it is worth having the option for tooltips. What are your thoughts?

All other changes have been made.

2024-11-17 18:34 UTC, phazonoverload commented
> Apexcharts doesn't have an option to change the funnel chart gap color. I can change it using CSS but it wouldn't match the chosen colour anymore. It would be need to be a static value or a css theme variable. 

Happy to leave it as-is given this. 

> The timeline opacity is for overlapping timelines. Do you still want the opacity changed to 1?

Also no - makes total sense. 

> I've removed the grouping from the timeline chart but since it's optional, wouldn't it be better to leave it in?

Nah - I'm a fan of more simple extensions at this point. Also, there was a significant creative review feedback for this mode that would have pushed our release deadline. 

> Rather than remove the hover tooltip on the treetop charts, I've disabled the tooltip by default. If they choose to hide the labels, I think it is worth having the option for tooltips. What are your thoughts?

Agree! 

@HimoriTempest can you give this one last look-over, but I think it might be good to go.

2024-11-17 20:49 UTC, phazonoverload commented
Oh just a small note @timio23 we'll need to redo the graphic in the readme for the timeline to not show grouping

2024-11-18 10:27 UTC, timio23 commented
@phazonoverload, I've updated that screenshot now

2024-11-18 11:17 UTC, HimoriTempest commented
@phazonoverload Looking good 🚀

2024-11-18 13:01 UTC, merged